title: "Ashley Puida's Journey"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.75
  brandStrength: 0
  lightness: 0.5657937475480139
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  rhythmicContrast: 0.9794295157771558
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Ashley Puida
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8931257
layout_spectrum: 1
