name: Ashley Puida
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07599
title: "Ashley Puida's Journey"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 1
  lightness: 0.5657937475480139
  saturation: 0.75
  rhythmicContrast: 0.9794295157771558
purpose: []
